### ISSUE TITLE
does not works on MS Windows

### ISSUE THREAD

**Issue by skyer9** [smartnews/jpa-entity-generator#32]
does not works on MS Windows.

no errors occurs, just does not create entity class.

tested on ms windows 10 and ubuntu(WSL).

**Comment by seratch** [comment]
Hello, I'm not sure if I will be able to help you but I'm curious about the issue. 

This library just writes text data using `java.nio.file.Files.write(Path, byte[])`. I'm pretty sure there are no OS-level dependencies. https://github.com/smartnews/jpa-entity-generator/blob/v0.99.8/src/main/java/com/smartnews/jpa_entity_generator/CodeGenerator.java#L209

How did you run the generator? Did you try the Gradle plugin or Maven plugin? Also, what happens if you run a simple Java program using the method as below?

```java
public class Sample {
  public static void main(String[] args) throws java.io.IOException {
    java.nio.file.Files.write(
      java.nio.file.Paths.get("hello.txt"),
      "Hello World!".getBytes()
    );
  }
}
// javac Sample.java
// java Sample
```

**Comment by skyer9** [comment]
i used intellij CE gradle on ms Windows 10,
and installed gradle on ubuntu(WSL) with `sudo apt install gradle`

log says file created but not exists

```
18:57:17.900 [DEBUG] [com.smartnews.jpa_entity_generator.CodeGenerator] path: src\main\java\com\example\entity\User.java, code: package com.example.entity;

import java.sql.*;
import javax.persistence.*;
import lombok.Data;

@Data
@Entity(name = "com.example.entity.User")
@Table(name = "wp_users")
```

**Comment by seratch** [comment]
It seems the source files might be created somewhere in your WSL filesystem location. I forgot the details but the root directory path would be like `AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_...`.

**Comment by skyer9** [comment]
a ha...
you're answer explains why no error occurred.
i wish fixing this issue.

**Comment by seratch** [comment]
You can try an absolute path for `outputDirectory` instead of `src/main/java`. It may work for you. https://github.com/smartnews/jpa-entity-generator/blob/v0.99.8/sample/src/main/resources/entityGenConfig.yml#L18

I don't think this library needs to fix something for this. The Gradle plugin works on Linux systems in general. I'm not sure how you ran the Gradle command yet but my understanding is that the command should work properly if you simply use WSL as a kind of a Linux system.

If you come up with a pull request for improvements for specific needs, I'm happy to review it.

**Comment by skyer9** [comment]
thank you for you'r answer.
i like this tool, because i just started applying jpa to legacy.
